=== Rodez-IUT/dut-info2-filmprovider-FlorianHyver/Part1-XML-DTD/Librairie.dtd
<!ELEMENT librairie (en-tête, livre+)>
        <!ELEMENT en-tête (#PCDATA|strong|em|img)*>
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT img EMPTY>
        <!ATTLIST img src CDATA #REQUIRED>
        <!ATTLIST img title CDATA #IMPLIED>
        <!ELEMENT livre (titre, auteurs, description, prix)>
        <!ATTLIST livre ISBN NMTOKEN #REQUIRED>
        <!ELEMENT titre (#PCDATA)>
        <!ELEMENT auteurs ((nom,prenom?)*|(direction, membre)) >
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prenom (#PCDATA)>
        <!ELEMENT direction (nom,prenom?)>
        <!ELEMENT membre (#PCDATA)>
        <!ELEMENT description (#PCDATA|strong|em|img)>
        <!ELEMENT prix (#PCDATA)>
        <!ATTLIST prix devise (euro|livre|dollar) "euro">
        <!ATTLIST prix type (HT|HTTC) "HT">
        <!ATTLIST prix tva #FIXED"5.5">

=== Rodez-IUT/dut-info2-filmprovider-FlorianHyver/Part1-XML-DTD/Librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <en-tête>Ceci est un en-tête de texte libre d'une <strong>LIBRAIRIE</strong> &copyright;</en-tête>
    <livre ISBN="TWHTR">
        <titre>The Witcher</titre>
        <auteurs>
            <nom>Sapkowski</nom>
            <prenom>Andrzej</prenom>
        </auteurs>
        <description>Le Sorceleur Geralt de Riv et un chasseur de monstre, plonger au sein d'un royaume en guerre</description>
        <prix devise="livre" tva="5.5" type="HT">19,99</prix>
    </livre>
    <livre ISBN="CBP">
        <titre>Cyberpunk 2077</titre>
        <auteurs>
            <collectif>
                <direction>
                    <nom>CD Project Red</nom>
                </direction>
                <membre>Jhon Doe</membre>
            </collectif>
        </auteurs>
        <description>Vous êtes un homme talentueux dans un monde futuriste</description>
        <prix tva="5.5" devise="euro" type="HTTC">64,99</prix>
    </livre>
</librairie>
